### ISSUE TITLE
command 'vscode-note.domain.create' not found

### ISSUE THREAD

**Issue by phhbr** [shinhwagk/vscode-note#1]
When I install the extension & relaunch VS Code, I get the additional tab for notes. But when I want to add a note, it says "command 'vscode-note.domain.create' not found".

vscode-note
Marketplace Version: v0.9.41

Visual Studio Code
Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

Do I have to set up something else?

**Comment by shinhwagk** [comment]
try update to lastest

**Comment by phhbr** [comment]
fixed. thanks
