### ISSUE TITLE
How to delete domain?

### ISSUE THREAD

**Issue by Tspm1eca** [shinhwagk/vscode-note#2]
I love this extension, but how to delete domain and search?

**Comment by shinhwagk** [comment]
search that uses the features provided by vscode 
![image](https://user-images.githubusercontent.com/10293294/65766951-009de000-e15f-11e9-8ebe-37a695b172e6.png)

no delete function yet, recommend create domain Trash then move .

**Comment by shinhwagk** [comment]
add a simple search for domain notes
