### ISSUE TITLE
Comfortable document editing

### ISSUE THREAD

**Issue by tbrandenburg** [shinhwagk/vscode-note#4]
Hello  shinhwagk,

1. Is there a comfortable (one-click?) way to edit markdown documents _again_?
2. Is it possible to also e.g. create asciidoc documents instead of markdown? Maybe via configuration of file extension?

Again thanks for that super cool extension!

Best regards,
Tom

**Comment by shinhwagk** [comment]
@tbrandenburg
Thank you for like vscode-note. 
1. How to edit comfortably, do you have any suggestions?
2. asciidoc is great, and a nice [extension](url) already exists, I will add it later
